Import Package

In [10]:
import tensorflow as tf

Test tf: validate tensorflow import

In [11]:
print(tf.__version__)


2.0.0


In [13]:
x = tf.print(1)
x = tf.random.normal(shape=(4,3))
tf.print(x)

1
[[0.750466108 0.48570919 -0.961181164]
 [-0.928294778 -0.53363806 -0.592513382]
 [0.934889376 0.287775189 -0.645297408]
 [0.529154181 0.542888045 1.50149858]]


In [14]:
tf.print(x*x)

[[0.563199401 0.235913411 0.923869252]
 [0.861731172 0.284769565 0.351072103]
 [0.874018133 0.0828145593 0.416408747]
 [0.280004144 0.294727415 2.254498]]


Tensors

In [16]:
print(x.shape)

(4, 3)


In [17]:
x.get_shape()

TensorShape([4, 3])

In [18]:
x.rank

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'rank'

In [19]:
x.dtype

tf.float32