Import Package

In [7]:
import tensorflow as tf

Test tf: validate tensorflow import

In [10]:
print(tf.__version__)


2.0.0


In [11]:
x = tf.print(1)
x = x=tf.random.normal(shape=(4,3))
tf.print(x)

1
[[-0.027738 0.744751 0.891893625]
 [2.03969741 -0.468081325 -1.30285382]
 [-0.314752847 -1.75578928 -1.45846784]
 [0.855094671 -0.673627853 0.16183424]]


In [13]:
tf.print(x*x)

[[0.000769396604 0.554654 0.795474231]
 [4.16036558 0.219100133 1.69742811]
 [0.0990693569 3.0827961 2.12712836]
 [0.731186926 0.453774482 0.0261903219]]
