First very simple Dense network, with no hidden layer.
Start from here to improve the model in later iterations
2 layers:
- Input: 64 units, sigmoid
- Output: 10 units, softmax

Import packages

In [306]:
#numpy: Numeric library
import numpy as np 
#graphics
from matplotlib import pyplot as plt

#tensorflow: use some TF tools
import tensorflow as tf
#Keras: Deep learning API. In TF 2.x, it is included in TF
from tensorflow import keras
#Import Dense layer
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras import Model
#Optimizers: SGD (Stochastic Gradien Descent)
#from tensorflow.keras.optimizers import SGD as sgd

#import data set MNIST
from tensorflow.keras.datasets import mnist

Some verifications

In [307]:
#TF
print(np.random.uniform())

0.4945749307698868


Import MNIST data set
60000 training examples
10000 validation examples
1 example = 28 * 28 matrix (image with 28 * 28 pixels)


In [308]:
(x_train, y_train), (x_valid, y_valid) = mnist.load_data()


In [309]:
print(x_train.shape)


(60000, 28, 28)


In [310]:
print(y_train.shape)

(60000,)


In [311]:
print(x_train[0].shape)

(28, 28)


In [312]:
print(y_train)
print(y_train.size)

[5 0 4 ... 5 6 8]
60000


In [313]:
print(x_valid.shape)
print(y_valid.shape)

(10000, 28, 28)
(10000,)


Process & Prepare data
Flattening Input data:
Input data (x_train[i]) should be a vector of real values
- From shape (60000, 28, 28) to shape (60000, 28 * 28)
- Convert to float32 (default is uint8, which python will convert to float64) (flaot 32 will take less memory)

In [314]:
#print(x_train[0])

In [315]:
#x_train.reshape(60000, 784).astype('float32')

In [316]:
#use numpy reshape
x_train = np.reshape(x_train, (60000, 28 * 28)).astype('float32')
x_valid = np.reshape(x_valid, (10000, 28 * 28)).astype('float32')

In [317]:
print(x_train.shape)
print(x_valid.shape)

(60000, 784)
(10000, 784)


Prepare Data (2)
divide by 255, so the values will range from 0 to 1


In [318]:
#print(x_train)
x_train /=  255
x_valid /=  255

In [319]:
#print(x_train[0])

Prepare labels (y_train and y_valid)
y_train[i] is given as a number (0, 9). We have 10 possible values. 
Convert to one-hot format:
0 => [1, 0, 0, 0, 0,0, 0,0, 0,0]
1 => [0, 1, 0, 0, 0,0, 0,0, 0,0]
9 => [0, 0, 0, 0, 0,0, 0,0, 0,1]

In [320]:
n_classes = 10
print(y_train[0])
y_train = keras.utils.to_categorical(y_train, n_classes)
print(y_train[0])

print(y_valid[0])
y_valid = keras.utils.to_categorical(y_valid, n_classes)
print(y_valid[0])


5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


Define Neural Network Architecture
Using Keras API

In [321]:
# Sequential: model of type sequential (layer n can pass information only to layer n+1)
model = Sequential()
model.to_json()

'{"class_name": "Sequential", "config": {"name": "sequential_11", "layers": []}, "keras_version": "2.2.4-tf", "backend": "tensorflow"}'

In [322]:
#Define activations
sigmoid = keras.activations.sigmoid
softmax = keras.activations.softmax

#define loss function
loss = keras.losses.mean_squared_error

#define metrics
metrics = [keras.metrics.Accuracy()]

#define optimizer
sgd=keras.optimizers.SGD()
print(sgd)

In [323]:
#define Input layer
inputSize = 28 * 28 # size of input vector
inputUnits = 64 #Number of input layer units (artificial neuron)
inputLayer = Dense(inputUnits, activation=  sigmoid, input_shape=(inputSize,))
model.add(inputLayer)

In [324]:
#define Output layer
 
outputUnits = 10 #Number of output layer units (artificial neuron)
# output shape will be inferred
outputLayer = Dense(outputUnits, activation=  softmax)
model.add(outputLayer)

In [325]:
#compile Model
model.compile(loss=loss, 
         optimizer=sgd,
         metrics=['accuracy'])

In [326]:
# print model summary
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 64)                50240     
_________________________________________________________________
dense_16 (Dense)             (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [327]:
# Train
batch_size = 128
nb_epoch = 10
model.fit(x_train, y_train, batch_size= batch_size, epochs = nb_epoch, verbose=1, validation_data=(x_valid, y_valid))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 1s 25us/sample - loss: 0.0926 - accuracy: 0.1543 - val_loss: 0.0922 - val_accuracy: 0.1598
Epoch 2/10
60000/60000 [==============================] - 1s 15us/sample - loss: 0.0917 - accuracy: 0.1734 - val_loss: 0.0913 - val_accuracy: 0.1772
Epoch 3/10
60000/60000 [==============================] - 1s 15us/sample - loss: 0.0909 - accuracy: 0.1898 - val_loss: 0.0906 - val_accuracy: 0.2035
Epoch 4/10
60000/60000 [==============================] - 1s 15us/sample - loss: 0.0903 - accuracy: 0.2382 - val_loss: 0.0900 - val_accuracy: 0.2720
Epoch 5/10
60000/60000 [==============================] - 1s 15us/sample - loss: 0.0897 - accuracy: 0.2889 - val_loss: 0.0895 - val_accuracy: 0.3070
Epoch 6/10
60000/60000 [==============================] - 1s 15us/sample - loss: 0.0893 - accuracy: 0.3074 - val_loss: 0.0891 - val_accuracy: 0.3190
Epoch 7/10
60000/60000 [==============================] 

In [ ]:
# summary
model.summary()