In [1]:
import tensorflow as tf

In [2]:
x= tf.range(12)
print(x)
x.shape

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


TensorShape([12])

In [3]:
print(x[0])

tf.Tensor(0, shape=(), dtype=int32)


In [4]:
tf.size(x)

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=12>

In [5]:
x.shape

TensorShape([12])

In [6]:
X = tf.reshape(x, (3, 4))
print(X)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


In [7]:
X = tf.reshape(x, (4, -1))
print(X)

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)


In [8]:
X = tf.reshape(x, (-1, 2))
print(X)

tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]], shape=(6, 2), dtype=int32)


In [9]:
Y = tf.zeros((2,  3, 4))

In [10]:
tf.reshape(Y, (-1,))

<tf.Tensor: id=19, shape=(24,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [11]:
tf.reshape(Y, (2,3,-1))

<tf.Tensor: id=21, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [12]:
Z = tf.ones((1000, 100000))

In [13]:
Z.shape

TensorShape([1000, 100000])

In [14]:
tf.random.normal((2, 3))

<tf.Tensor: id=30, shape=(2, 3), dtype=float32, numpy=
array([[0.49228057, 1.1084286 , 1.6981337 ],
       [0.00829166, 1.3875483 , 0.7171227 ]], dtype=float32)>

In [15]:
tf.random.normal((2, 3), -2, 1)

<tf.Tensor: id=36, shape=(2, 3), dtype=float32, numpy=
array([[-1.7056819, -1.7026196, -2.496129 ],
       [-1.8412044, -1.7018927, -1.360469 ]], dtype=float32)>

In [16]:
tf.random.normal((2, 3), 2, 1)

<tf.Tensor: id=42, shape=(2, 3), dtype=float32, numpy=
array([[2.169958  , 2.800726  , 0.32656455],
       [2.601099  , 2.499468  , 2.2792807 ]], dtype=float32)>

In [17]:
import numpy as np

In [18]:
a = np.array([[1, 2], [3, 4]])

In [19]:
tf.constant(a)

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [20]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(<tf.Tensor: id=46, shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: id=47, shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: id=48, shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: id=49, shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: id=50, shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [21]:
tf.exp(x)

<tf.Tensor: id=51, shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598152e+01, 2.9809580e+03],
      dtype=float32)>

In [22]:
tf.cos(x)

<tf.Tensor: id=52, shape=(4,), dtype=float32, numpy=array([ 0.5403023 , -0.4161468 , -0.6536436 , -0.14550003], dtype=float32)>

In [23]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: id=64, shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: id=66, shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

In [24]:
X == Y

<tf.Tensor: id=67, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [25]:
X != Y

<tf.Tensor: id=68, shape=(3, 4), dtype=bool, numpy=
array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [26]:
X -1 == Y +1

<tf.Tensor: id=73, shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [27]:
3 * X

<tf.Tensor: id=75, shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  3.,  6.,  9.],
       [12., 15., 18., 21.],
       [24., 27., 30., 33.]], dtype=float32)>

In [28]:
X * 3

<tf.Tensor: id=77, shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  3.,  6.,  9.],
       [12., 15., 18., 21.],
       [24., 27., 30., 33.]], dtype=float32)>

In [29]:
X / 4

<tf.Tensor: id=79, shape=(3, 4), dtype=float32, numpy=
array([[0.  , 0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 , 1.75],
       [2.  , 2.25, 2.5 , 2.75]], dtype=float32)>

In [30]:
tf.reduce_sum(X)

<tf.Tensor: id=81, shape=(), dtype=float32, numpy=66.0>

In [31]:
tf.reduce_prod(Y+1)

<tf.Tensor: id=85, shape=(), dtype=float32, numpy=1728000.0>

In [32]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: id=91, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: id=97, shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [33]:
a+b

<tf.Tensor: id=98, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [34]:
X[-1], X[1:3]

(<tf.Tensor: id=102, shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: id=106, shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [35]:
X

<tf.Tensor: id=61, shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [36]:
X_Var = tf.Variable(X)
X_Var[1, 2]

<tf.Tensor: id=118, shape=(), dtype=float32, numpy=6.0>

In [37]:
X_Var[1, 2].assign(2)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  2.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [38]:
X, X_Var

(<tf.Tensor: id=61, shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  2.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [39]:
id(Y)

2194125634200

In [40]:
id(X)

2194125623544

In [41]:
Y = X + Y

In [42]:
id(X),id(Y)

(2194125623544, 2193980289448)

In [43]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 2193980318984
id(Z): 2193980318984


In [44]:
tf.zeros(2),tf.zeros_like(X)

(<tf.Tensor: id=138, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Tensor: id=139, shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

In [45]:
tf.zeros_like

<function tensorflow.python.ops.array_ops.zeros_like_v2(input, dtype=None, name=None)>

In [46]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # This unused value will be pruned out
    A = X + Y  # Allocations will be re-used when no longer needed
    B = A + Y
    C = B + Y
    print(len(X), id(X), id(Y), id(A), id(B), id(C), id(Z))
    return C + Y



In [47]:
computation(X, Y)

3 2194125628936 2193980321288 2194126499016 2194126044936 2194126332232 2194126042568


<tf.Tensor: id=151, shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  9., 26., 27.],
       [24., 33., 42., 51.],
       [56., 57., 58., 59.]], dtype=float32)>

In [48]:
computation(X+1, Y*2)

<tf.Tensor: id=156, shape=(3, 4), dtype=float32, numpy=
array([[ 17.,  18.,  51.,  52.],
       [ 45.,  62.,  79.,  96.],
       [105., 106., 107., 108.]], dtype=float32)>

In [50]:
A = X.numpy()
B = tf.constant(A)
type(X), type(A), type(B)

(tensorflow.python.framework.ops.EagerTensor,
 numpy.ndarray,
 tensorflow.python.framework.ops.EagerTensor)

In [51]:
import d2l 

In [53]:
import d2l.tensorflow

ModuleNotFoundError: No module named 'requests'