In [1]:
import tensorflow as tf


In [2]:
x = tf.constant([3.0])
y = tf.constant([2.0])

x + y, x * y, x / y, x**y

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>,
 <tf.Tensor: id=3, shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>,
 <tf.Tensor: id=4, shape=(1,), dtype=float32, numpy=array([1.5], dtype=float32)>,
 <tf.Tensor: id=5, shape=(1,), dtype=float32, numpy=array([9.], dtype=float32)>)

In [3]:
x = tf.range(4)
x

<tf.Tensor: id=9, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [6]:
len(x)

4

In [7]:
x.shape

TensorShape([4])

In [10]:
tf.size(x)

<tf.Tensor: id=14, shape=(), dtype=int32, numpy=4>

In [18]:
A = tf.reshape(tf.range(20), (5, 4))
A

<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [13]:
A[3, 1]

<tf.Tensor: id=28, shape=(), dtype=int32, numpy=13>

In [14]:
A[:3, 1]

<tf.Tensor: id=32, shape=(3,), dtype=int32, numpy=array([1, 5, 9])>

In [15]:
A[2, :2]

<tf.Tensor: id=36, shape=(2,), dtype=int32, numpy=array([8, 9])>

In [19]:
A, tf.transpose(A)

(<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])>,
 <tf.Tensor: id=48, shape=(4, 5), dtype=int32, numpy=
 array([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])>)

In [21]:
A.shape == tf.transpose(A).shape

False

In [22]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

<tf.Tensor: id=53, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

In [23]:
B.shape == tf.transpose(B).shape

True

In [25]:
B == tf.transpose(B)

<tf.Tensor: id=60, shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [26]:
C = A * A

In [27]:
C

<tf.Tensor: id=61, shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])>

In [28]:
tf.reduce_sum(A)

<tf.Tensor: id=63, shape=(), dtype=int32, numpy=190>

In [32]:
A,tf.reduce_sum(A, axis=[0])

(<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])>,
 <tf.Tensor: id=73, shape=(4,), dtype=int32, numpy=array([40, 45, 50, 55])>)

In [34]:
A,tf.reduce_sum(A, axis=[1])

(<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])>,
 <tf.Tensor: id=77, shape=(5,), dtype=int32, numpy=array([ 6, 22, 38, 54, 70])>)

In [35]:
A,tf.reduce_mean(A, axis=[0])

(<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])>,
 <tf.Tensor: id=79, shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11])>)

In [41]:
A.shape[0]

5

In [43]:
tf.reduce_sum(A, axis=[0]) / A.shape[0]

<tf.Tensor: id=113, shape=(4,), dtype=float64, numpy=array([ 8.,  9., 10., 11.])>

In [46]:
tf.cast(A, tf.float32)

<tf.Tensor: id=122, shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [48]:
tf.reduce_mean(tf.cast(A, tf.double), axis=[0]) == tf.reduce_sum(A, axis=[0]) / A.shape[0]

<tf.Tensor: id=141, shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [50]:
tf.reduce_max(A, axis=[0])

<tf.Tensor: id=145, shape=(4,), dtype=int32, numpy=array([16, 17, 18, 19])>

In [51]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: id=147, shape=(5, 1), dtype=int32, numpy=
array([[ 6],
       [22],
       [38],
       [54],
       [70]])>

In [52]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: id=149, shape=(5,), dtype=int32, numpy=array([ 6, 22, 38, 54, 70])>

In [53]:
A / sum_A

<tf.Tensor: id=152, shape=(5, 4), dtype=float64, numpy=
array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])>

In [58]:
x = tf.range(4, dtype=tf.float32)
y = tf.ones(4, dtype=tf.float32)
x, y, tf.tensordot(x, y, axes=1)

(<tf.Tensor: id=189, shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: id=192, shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Tensor: id=203, shape=(), dtype=float32, numpy=6.0>)

In [66]:
tf.reduce_sum(x * y)

<tf.Tensor: id=251, shape=(), dtype=float32, numpy=6.0>

In [67]:
tf.reduce_sum(x * y) == tf.tensordot(x, y, axes=1)

<tf.Tensor: id=266, shape=(), dtype=bool, numpy=True>

In [74]:
x = tf.range(4, dtype=tf.int32)
A,x,A.shape,x.shape

(<tf.Tensor: id=46, shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])>,
 <tf.Tensor: id=294, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>,
 TensorShape([5, 4]),
 TensorShape([4]))

In [75]:
 
tf.linalg.matvec(A, x)

<tf.Tensor: id=298, shape=(5,), dtype=int32, numpy=array([ 14,  38,  62,  86, 110])>

In [76]:
tf.tensordot(A, x, axes=0)

<tf.Tensor: id=309, shape=(5, 4, 4), dtype=int32, numpy=
array([[[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6],
        [ 0,  3,  6,  9]],

       [[ 0,  4,  8, 12],
        [ 0,  5, 10, 15],
        [ 0,  6, 12, 18],
        [ 0,  7, 14, 21]],

       [[ 0,  8, 16, 24],
        [ 0,  9, 18, 27],
        [ 0, 10, 20, 30],
        [ 0, 11, 22, 33]],

       [[ 0, 12, 24, 36],
        [ 0, 13, 26, 39],
        [ 0, 14, 28, 42],
        [ 0, 15, 30, 45]],

       [[ 0, 16, 32, 48],
        [ 0, 17, 34, 51],
        [ 0, 18, 36, 54],
        [ 0, 19, 38, 57]]])>

In [89]:
B = tf.ones((4, 8), tf.int32)
A.shape, B.shape,A.shape[1] == B.shape[0]


(TensorShape([5, 4]), TensorShape([4, 8]), True)

In [90]:
 
tf.matmul(A, B)

<tf.Tensor: id=341, shape=(5, 8), dtype=int32, numpy=
array([[ 6,  6,  6,  6,  6,  6,  6,  6],
       [22, 22, 22, 22, 22, 22, 22, 22],
       [38, 38, 38, 38, 38, 38, 38, 38],
       [54, 54, 54, 54, 54, 54, 54, 54],
       [70, 70, 70, 70, 70, 70, 70, 70]])>

In [95]:
#L2 Norm
u = tf.constant([3.0, -4.0])
u,tf.norm(u)

(<tf.Tensor: id=351, shape=(2,), dtype=float32, numpy=array([ 3., -4.], dtype=float32)>,
 <tf.Tensor: id=356, shape=(), dtype=float32, numpy=5.0>)

In [105]:
x = tf.cast(tf.range(4), tf.float32)
x,u

(<tf.Tensor: id=382, shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: id=351, shape=(2,), dtype=float32, numpy=array([ 3., -4.], dtype=float32)>)

In [106]:
tf.norm(x)

<tf.Tensor: id=387, shape=(), dtype=float32, numpy=3.7416575>

In [110]:
tf.sqrt(tf.reduce_sum(u*u)) == tf.norm(u)

<tf.Tensor: id=407, shape=(), dtype=bool, numpy=True>

In [107]:
#L1 Norm
tf.reduce_sum(tf.abs(u))

<tf.Tensor: id=390, shape=(), dtype=float32, numpy=7.0>

In [111]:
tf.transpose(tf.transpose(A)) == A

<tf.Tensor: id=412, shape=(5, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [114]:
C = A + 2

In [116]:
tf.transpose(A) + tf.transpose(C) == tf.transpose(A + C)

<tf.Tensor: id=434, shape=(4, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [122]:
D = tf.reshape(tf.range(24), (2, 3, 4))
D

<tf.Tensor: id=458, shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [124]:
len(D) == D.shape[0] == 2

True